/*******************************************************************************
*                                                                              *
*                         CanonicalEmptySnapshot                               *
*                                                                              *
*******************************************************************************/

// canonical binary snapshot of a freshly initialised, empty SDS_NoteStore

// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  WARNING — DO NOT REGENERATE THIS SNAPSHOT CASUALLY                      ║
// ║                                                                          ║
// ║  this byte array encodes the internal json-joy CRDT node-ID space that   ║
// ║  ALL peers share.  every store loaded via SDS_NoteStore.fromScratch()    ║
// ║  starts from exactly these bytes.  if the snapshot is replaced with      ║
// ║  freshly generated bytes, the new node-ID space will be different from   ║
// ║  the old one, making ALL existing persisted stores and patches           ║
// ║  PERMANENTLY INCOMPATIBLE with stores created from the new snapshot.     ║
// ║                                                                          ║
// ║  regeneration is only ever justified when:                               ║
// ║    1. the SNS entry schema changes (new top-level CRDT fields), AND      ║
// ║    2. you accept that existing data cannot be migrated and will be lost. ║
// ║                                                                          ║
// ║  if you need to regenerate, follow the instructions in                   ║
// ║  scripts/generate-canonical-snapshot.test.ts — and do so deliberately,   ║
// ║  never as part of a build or CI step.                                    ║
// ╚══════════════════════════════════════════════════════════════════════════╝

/**** WHY this exists ****/

// json-joy assigns internal CRDT node IDs based on a site counter that is
// seeded non-deterministically at model creation time.  two independent
// Model.create() calls therefore produce incompatible ID spaces — patches
// from one cannot be applied to the other.
//
// by shipping one canonical snapshot and having fromScratch() load it via
// fromBinary(), every peer starts from the same CRDT state.  patches from
// any two such peers are automatically compatible.

/**** WHAT is stored here ****/

// a gzip-compressed json-joy binary snapshot containing exactly the three
// well-known notes (RootNote, TrashNote, LostAndFoundNote) in their initial
// state, with their fixed UUIDs and default labels.
//
// generated with: json-joy ^17.65.0
// length: 290 bytes (gzip-compressed CRDT snapshot)
// generated by: scripts/generate-canonical-snapshot.test.ts (run manually)

export const CanonicalEmptySnapshot = new Uint8Array([
  31, 139, 8, 0, 235, 111, 170, 105, 0, 3, 165, 207, 207, 74, 195, 64,
  16, 6, 240, 232, 197, 170, 208, 179, 138, 173, 171, 22, 4, 53, 154,
  138, 104, 241, 15, 40, 53, 106, 72, 211, 86, 16, 239, 91, 119, 138,
  133, 184, 145, 100, 3, 219, 91, 191, 55, 17, 95, 196, 135, 208, 71,
  16, 244, 49, 172, 73, 10, 241, 32, 4, 156, 195, 192, 12, 51, 124, 252,
  12, 99, 122, 3, 221, 115, 61, 99, 75, 21, 14, 40, 66, 167, 169, 107,
  86, 86, 102, 210, 246, 127, 90, 99, 50, 78, 10, 109, 91, 184, 3, 41,
  224, 25, 66, 6, 138, 168, 197, 123, 228, 163, 197, 224, 142, 132, 35,
  251, 1, 156, 51, 93, 242, 28, 207, 190, 29, 62, 17, 174, 25, 174, 70,
  122, 246, 142, 251, 49, 37, 111, 54, 195, 5, 208, 28, 255, 74, 42,
  148, 88, 199, 233, 101, 154, 120, 146, 38, 234, 114, 16, 43, 10, 187,
  62, 191, 167, 71, 146, 10, 199, 12, 71, 198, 139, 158, 79, 214, 237,
  241, 133, 35, 138, 89, 116, 169, 19, 10, 10, 93, 26, 246, 184, 149,
  65, 26, 12, 135, 192, 1, 169, 144, 71, 15, 41, 200, 202, 131, 118,
  25, 118, 126, 129, 182, 25, 182, 128, 205, 226, 160, 61, 212, 50, 208,
  250, 31, 160, 53, 134, 213, 127, 131, 234, 25, 104, 133, 161, 10, 84,
  116, 217, 15, 34, 101, 114, 41, 204, 126, 16, 75, 145, 208, 170, 57,
  89, 133, 45, 231, 93, 75, 108, 17, 11, 9, 106, 234, 249, 235, 253,
  245, 237, 227, 115, 238, 230, 27, 200, 123, 156, 72, 53, 2, 0, 0,
])
